TNT-38730 Remove clientCode URL params to Delivery API from Java SDK
adobe/target-java-sdk pull request #18
Opened 2020-11-02 21:04 UTC by mptap

Removed clientCode URL params to Delivery API from Java SDK

## Description

## Related Issue

https://jira.corp.adobe.com/browse/TNT-38731

## Motivation and Context

A change to Delivery API by Aditi Shete will be deployed on 21 Oct, 2020.  The Delivery API will no longer require BOTH imsOrg and clientCode as params.  Only imsOrg is sufficient because org and client code are 1-1 mapping.

The change to Delivery API would not impact SDK but SDK should be consistent with the backend APIs. 

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2020-11-02 23:18 UTC, 5amfung reviewed
Is `All new and existing tests passed` checked?

Please build it and test locally against delievery API if you haven't already.

2020-11-02 23:54 UTC, mptap commented
Yes I already have passing tests locally.

2020-11-18 23:46 UTC, artur-ciocanu requested changes
@mptap I don't see `organizationId` being used anywhere. We have `DefaultTargetService` where we add `client` query string parameter. Here we should remove the `client` query string parameter and replace it with `imsOrgId`.

Whenever you have a chance please adjust and resend.

2020-11-19 04:03 UTC, artur-ciocanu approved these changes
Looks good.

2020-11-19 04:05 UTC, merged