TNT-40658 - updated openapi models using customized resttemplate java generator
adobe/target-java-sdk pull request #35
Opened 2021-08-18 04:02 UTC by dcottingham

These models were created using a customized openapi java generator, along with customized templates.  In order to automate model generation I will need to fork this repo and add my custom java generator code since all customizations could not be made via templates alone:  https://github.com/OpenAPITools/openapi-generator

2021-08-20 09:39 UTC, artur-ciocanu requested changes
@dcottingham I have left some comments, overall the changes are great. However we have to be careful around moving currently exposed classes to other places.

Ideally we should have tests that would ensure that classes available on `com.adobe.target.edge.client.model` are available and working as expected. Otherwise if customers will upgrade and we moved something to a different package, their code might fail.

2021-08-20 09:39 UTC, artur-ciocanu commented on src/main/java/com/adobe/target/delivery/v1/model/MboxResponse.java
>  public class MboxResponse {
@dcottingham please make sure that this is expected. I am not sure why we have `$_type`.

2021-08-20 09:39 UTC, artur-ciocanu commented on src/main/java/com/adobe/target/delivery/v1/model/RequestDetails.java
>  public class RequestDetails {
Same here, it's not clear why we need `$_type`.

2021-08-20 09:39 UTC, artur-ciocanu commented on src/test/java/com/adobe/target/edge/client/entities/TargetDeliveryLocalGeoTest.java
You should probably configure your IDE to do not collapse imports.

2021-08-20 09:39 UTC, artur-ciocanu commented on src/test/java/com/adobe/target/edge/client/entities/TargetDeliveryLocalPropertyTest.java
Same here

2021-08-31 16:55 UTC, jasonwaters approved these changes
LGTM!

2021-08-31 19:50 UTC, merged